version: '2'
services:
    db:
        container_name: db_tictactoe
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql.conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_DATABASE: tictactoe
            MYSQL_USER: tictactoe
            MYSQL_PASSWORD: tictactoe
            MYSQL_ROOT_PASSWORD: root

    redis:
        container_name: redis_tictactoe
        image: redis
        ports:
            - "6379:6379"

    php:
        container_name: php_tictactoe
        build: ./php-fpm
        environment:
            XDEBUG_CONFIG: remote_host=172.17.0.1
            PHP_IDE_CONFIG: serverName=docker
        expose:
            - "9000"
        volumes:
            - ./php-fpm/symfony.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./.composer:/var/www/.composer
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db

    nginx:
        container_name: nginx_tictactoe
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./certificates/:/etc/ssl

#    rabbitmq:
#        container_name: rabbitmq_tictactoe
#        build: ./rabbitmq_stomp
#        ports:
#            - 61613:61613
#            - 15674:15674
#            - 15672:15672

    elk:
        container_name: kibana_tictactoe
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
            - ./elk/elasticsearch:/var/lib/elasticsearch
        volumes_from:
            - php
            - nginx
