services:
    tic_tac_toe.domain.doctrine.doctrine_factory.game:
        class: TicTacToe\Domain\GameBundle\Doctrine\DoctrineFactory
        arguments: ['@doctrine']

    tic_tac_toe.domain.doctrine.unit_of_work.game:
        class: TicTacToe\InfrastructureBundle\ORM\IUnitOfWork
        factory: ['@tic_tac_toe.domain.doctrine.doctrine_factory.game', createUnitOfWork]

    tic_tac_toe.domain.repository.game:
        class: TicTacToe\InfrastructureBundle\ORM\IRepository
        factory: ['@tic_tac_toe.domain.doctrine.doctrine_factory.game', createGameRepository]