services:
    tic_tac_toe.domain.doctrine.doctrine_factory.move:
        class: TicTacToe\Domain\MoveBundle\Doctrine\DoctrineFactory
        arguments: ['@doctrine']

    tic_tac_toe.domain.doctrine.unit_of_work.move:
        class: TicTacToe\InfrastructureBundle\ORM\IUnitOfWork
        factory: ['@tic_tac_toe.domain.doctrine.doctrine_factory.move', createUnitOfWork]

    tic_tac_toe.domain.repository.move:
        class: TicTacToe\InfrastructureBundle\ORM\IRepository
        factory: ['@tic_tac_toe.domain.doctrine.doctrine_factory.move', createMoveRepository]